//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.SocialMedias = new HashSet<SocialMedia>();
        }
    
        public int AccountID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> AddedBy { get; set; }
        public string AddedOn { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<SocialMedia> SocialMedias { get; set; }
    }
}
