//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocialMedia
    {
        public int SocialMediaID { get; set; }
        public Nullable<int> Type { get; set; }
        public string Password { get; set; }
        public string Savedon { get; set; }
        public string Createdon { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual User User { get; set; }
        public virtual Account Account { get; set; }
    }
}
